import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./components/Providers";
import { ReactQueryProvider } from "./lib/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <ReactQueryProvider>
        <Providers>
          <body className={inter.className}>{children}</body>
        </Providers>
      </ReactQueryProvider>
    </html>
  );
}
